version: '3'

networks:
  node-networks:
    driver: bridge

services:
  api:
    build: .
    container_name: node-api
    command: npm run dev
    tty: true
    depends_on:
      - mariadb
      - redis
    networks:
      - node-networks
    volumes:
      - .:/home/api
      - /home/api/node_modules
    ports:
      - 3333:3333

  # Commented because it still doesn't work on the ARM chip (M1)
  #
  #  mysql:
  #    image: mysql:8
  #    container_name: node-mysql
  #    tty: true
  #    networks:
  #      - node-networks
  #    ports:
  #      - 3306:3306
  #    volumes:
  #      - .docker/mysql:/var/lib/mysql
  #    environment:
  #      MYSQL_USER: root
  #      MYSQL_PASSWORD: root
  #      MYSQL_DATABASE: development
  #      MYSQL_ROOT_PASSWORD: root

  mariadb:
    image: mariadb
    tty: true
    restart: always
    container_name: node-mariadb
    networks:
      - node-networks
    ports:
      - '3306:3306'
    volumes:
      - '.docker/mysql/config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
      - '.docker/mysql/data:/var/lib/mysql'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  redis:
    image: bitnami/redis:latest
    container_name: node-redis
    tty: true
    networks:
      - node-networks
    ports:
      - 6379:6379
    volumes:
      - .docker/redis:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: redis
      ALLOW_EMPTY_PASSWORD: 'no'
