version: '3'

networks:
  mysql:

services:
  api:
    build: .
    container_name: api
    command: yarn dev
    tty: true
    depends_on:
      - mysql
    networks:
      - mysql
    links:
      - mysql
    volumes:
      - .:/home/api
      - /home/api/node_modules
    ports:
      - 3333:3333

  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    tty: true
    networks:
      - mysql
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: development
      MYSQL_ROOT_PASSWORD: root
